openapi: 3.0.0
info:
  title: AMZ API
  version: 1.0.0
  description: API For AMZ Dashboard
servers:
  - url: "/api"
    description: Server For AMZ Dashboard

#Paths for PMM

paths:
  /addPmm:
    post:
      tags:
        - Admin
      summary: Adding a PMM
      description: Add a PMM
      operationId: insertPmm
      requestBody:
        description: Get User details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - name
                - password
              properties:
                username:
                  type: string
                email:
                  type: string
                name:
                  type: string
                facebookLink:
                  type: number
                whatsAppNumber:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /loginPmm:
    post:
      tags:
        - PMM
      summary: Get test Response
      description: this is test request
      operationId: loginPMM
      requestBody:
        description: Get user credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /verifySessionToken:
    post:
      tags:
        - PMM
      summary: Get PMM
      description: this is to verify session token
      security:
        - access: ["pmmAuth"]
      operationId: verifySessionToken
      requestBody:
        description: Get user token
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getPmm:
    post:
      tags:
        - PMM
      summary: Get PMM
      description: this is to fetch PMM details
      security:
        - access: ["pmmAuth"]
      operationId: getUser
      requestBody:
        description: Get user details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: number

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /updatePmm:
    patch:
      tags:
        - PMM
      summary: Update PMM
      description: this is to update PMM details
      security:
        - access: ["pmmAuth"]
      operationId: updateUser
      requestBody:
        description: Get user details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: number

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /deletePmm:
    delete:
      tags:
        - Tasks
      summary: Deletes PMM
      description: this is to delete PMM
      operationId: deleteUser
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getAllOrders/:id:
    get:
      tags:
        - Orders
      summary: Get Orders
      description: this is to fetch PMM details
      security:
        - access: ["pmmAuth"]
      operationId: getAllOrders

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getOrdersByStatus/:id/:OrderStatusid:
    get:
      tags:
        - Orders
      summary: Get Orders
      description: this is to fetch PMM details
      security:
        - access: ["pmmAuth"]
      operationId: getOrdersByStatus

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /addProduct:
    post:
      tags:
        - Products
      summary: Add Product
      description: this is to add Product
      security:
        - access: ["pmmAuth"]
      operationId: addProduct
      requestBody:
        description: Get User details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: OK
          content:
            "application/json": {}
  /updateProductImage:
    post:
      tags:
        - Products
      summary: Add Product image
      description: this is to add Product image
      security:
        - access: ["pmmAuth"]
      x-middleware:
        - uploadFile
      operationId: updateProductImage
      requestBody:
        description: Get Product Image
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: number
                imageForUpload:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getAllProducts:
    post:
      tags:
        - Products
      summary: Get Products
      description: this is to fetch Products
      security:
        - access: ["pmmAuth"]
      operationId: getAllProducts
      requestBody:
        description: Get Products
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: number
                ProductcategoryId: 
                  type: number
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getProductsByStatus:
    post:
      tags:
        - Products
      summary: Get Product Categories
      description: this is to fetch Product Categories
      security:
        - access: ["pmmAuth"]
      operationId: getAllProducts
      requestBody:
        description: Get User details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: number
                status: 
                  type: boolean
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getProductsByCategory:
    post:
      tags:
        - Products
      summary: Get Product by Categories
      description: this is to fetch Product by Categories
      security:
        - access: ["pmmAuth"]
      operationId: getAllProducts
      requestBody:
        description: Get Products
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: number
                ProductcategoryId: 
                  type: number
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getProductCategories:
    get:
      tags:
        - Products
      summary: Get Product Categories
      description: this is to fetch Product Categories
      operationId: getProductCategories

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getAllReservations:
    post:
      tags:
        - Reservations
      summary: Get Reservations
      description: this is to fetch Reservations
      security:
        - access: ["pmmAuth"]
      operationId: getAllReservations
      requestBody:
        description: Get Reservations
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                PmmId: 
                  type: number
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

components:
  schemas:
    Product:
      type: object
      properties:
        PmmId:
          type: number
        keyword:
          type: string
        brandName:
          type: string
        soldBy:
          type: string
        market:
          type: string
        chineseSeller:
          type: string
        commission:
          type: number
        pmnlCommission:
          type: number
        dailySaleLimit:
          type: number
        overallSaleLimit:
          type: number
        ProductcategoryId:
          type: number
        instructions:
          type: string
        refundCondition:
          type: string
        commissionCondition:
          type: string
        picture:
          type: string
        amazonPicture:
          type: string
        status:
          type: boolean
