openapi: 3.0.0
info:
  title: AMZ API
  version: 1.0.0
  description: API For AMZ Dashboard
servers:
  - url: "/api"
    description: Server For AMZ Dashboard

#Paths for PMM
paths:
  /addPmm:
    post:
      tags:
        - Admin
      summary: Adding a PMM
      description: Add a PMM
      operationId: insertPmm
      requestBody:
        description: Get User details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - age
                - email
                - password
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                age:
                  type: number
                password:
                  type: string
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /loginPmm:
    post:
      tags:
        - PMM
      summary: Get test Response
      description: this is test request
      operationId: loginPMM
      requestBody:
        description: Get user credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /verifySessionToken:
    post:
      tags:
        - PMM
      summary: Get PMM
      description: this is to verify session token
      security:
        - access: ["pmmAuth"]
      operationId: verifySessionToken
      requestBody:
        description: Get user token
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getPmm:
    post:
      tags:
        - PMM
      summary: Get PMM
      description: this is to fetch PMM details
      security:
        - access: ["pmmAuth"]
      operationId: getUser
      requestBody:
        description: Get user details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: number

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /updatePmm:
    patch:
      tags:
        - PMM
      summary: Update PMM
      description: this is to update PMM details
      security:
        - access: ["pmmAuth"]
      operationId: updateUser
      requestBody:
        description: Get user details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: number

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /deletePmm:
    delete:
      tags:
        - Tasks
      summary: Deletes PMM
      description: this is to delete PMM
      operationId: deleteUser
      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getAllOrders/:id:
    get:
      tags:
        - Orders
      summary: Get Orders
      description: this is to fetch PMM details
      security:
        - access: ["pmmAuth"]
      operationId: getAllOrders

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

  /getOrdersByStatus/:id/:OrderStatusid:
    get:
      tags:
        - Orders
      summary: Get Orders
      description: this is to fetch PMM details
      security:
        - access: ["pmmAuth"]
      operationId: getOrdersByStatus

      responses:
        "200":
          description: OK
          content:
            "application/json": {}

